from pathlib import Path
import json
import tempfile
import unittest
from unittest.mock import patch

from agent_orchestrator import state as state_module
from agent_orchestrator.orchestrator import run_issue


class DryRunTests(unittest.TestCase):
    def test_dry_run_skips_github_mutations_and_pr_creation(self):
        issue = {
            "number": 42,
            "title": "Dry run issue",
            "body": "Test body",
            "state": "open",
            "url": "https://example.invalid/issues/42",
            "labels": [{"name": "agent-run"}],
        }

        with tempfile.TemporaryDirectory() as tmp:
            config_path = Path(tmp) / "orchestrator.json"
            state_root = Path(tmp) / "runs"
            config_path.write_text(
                """
{
  "model": "gpt-5.4-mini",
  "base_branch": "main",
  "work_branch_prefix": "agent/issue-",
  "max_cycles": 1,
  "commit_message_template": "agent(issue #{issue}): implement planned change",
  "labels": {
    "queue": "agent-run",
    "running": "agent-running",
    "blocked": "agent-blocked",
    "ready": "agent-ready-for-human",
    "failed": "agent-failed",
    "done": "agent-done"
  },
  "limits": {
    "max_changed_files": 30,
    "max_diff_lines": 1200
  },
  "forbidden_paths": [".env"],
  "test_commands": ["python -m unittest discover -s tests -p \\"test_*.py\\""],
  "codex": {
    "approval": "never",
    "builder_sandbox": "workspace-write",
    "reviewer_sandbox": "read-only",
    "planner_sandbox": "read-only",
    "extra_args": []
  },
  "pr": {
    "draft": true,
    "title_template": "Agent PR for issue #{issue}: {title}",
    "body_footer": "Generated by local Codex multi-agent orchestrator. Human review required before merge."
  }
}
""".strip(),
                encoding="utf-8",
            )

            with patch.object(state_module, "STATE_ROOT", state_root), \
                patch("agent_orchestrator.orchestrator.issue_view", return_value=issue), \
                patch("agent_orchestrator.orchestrator.add_label_to_issue") as add_label, \
                patch("agent_orchestrator.orchestrator.remove_label_from_issue") as remove_label, \
                patch("agent_orchestrator.orchestrator.comment_issue") as comment_issue, \
                patch("agent_orchestrator.orchestrator.create_or_checkout_branch") as checkout_branch, \
                patch("agent_orchestrator.orchestrator.commit_all") as commit_all, \
                patch("agent_orchestrator.orchestrator.push_branch") as push_branch, \
                patch("agent_orchestrator.orchestrator.pr_view_by_head") as pr_view_by_head, \
                patch("agent_orchestrator.orchestrator.create_pr") as create_pr, \
                patch("agent_orchestrator.orchestrator.ensure_clean_worktree") as clean_worktree, \
                patch("agent_orchestrator.orchestrator.has_changes", return_value=False), \
                patch("agent_orchestrator.orchestrator.changed_files", return_value=[]), \
                patch("agent_orchestrator.orchestrator.diff_line_count", return_value=0), \
                patch("agent_orchestrator.orchestrator._test_report", return_value=(True, "tests ok")), \
                patch("agent_orchestrator.orchestrator.run_codex_role") as run_codex_role:
                run_codex_role.return_value.ok = True
                run_codex_role.return_value.stderr = ""
                run_codex_role.return_value.stdout = "REVIEW_DECISION: approve"

                code = run_issue(42, config_path=str(config_path), dry_run=True)

            run_json = json.loads((state_root / "issue-42" / "run.json").read_text(encoding="utf-8"))
            summary = (state_root / "issue-42" / "summary.md").read_text(encoding="utf-8")

        self.assertEqual(code, 0)
        self.assertEqual(run_json["final_decision"], "approve")
        self.assertIn("- Final decision: `approve`", summary)
        add_label.assert_not_called()
        remove_label.assert_not_called()
        comment_issue.assert_not_called()
        checkout_branch.assert_not_called()
        clean_worktree.assert_not_called()
        commit_all.assert_not_called()
        push_branch.assert_not_called()
        pr_view_by_head.assert_not_called()
        create_pr.assert_not_called()


if __name__ == "__main__":
    unittest.main()
