from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

from agent_orchestrator.orchestrator import run_issue
from agent_orchestrator.shell import CommandResult


class BuilderSnapshotTests(unittest.TestCase):
    def test_builder_changes_are_committed_and_pushed_before_review(self):
        issue = {
            "number": 42,
            "title": "Snapshot issue",
            "body": "Test body",
            "state": "open",
            "url": "https://example.invalid/issues/42",
            "labels": [{"name": "agent-run"}],
        }
        events = []

        def fake_codex_role(*, role, variables, output_path=None, **kwargs):
            events.append(role)
            if role == "reviewer":
                self.assertIn("core/file.py", variables["diff_text"])
                return CommandResult(["codex"], 0, "REVIEW_DECISION: approve", "")
            return CommandResult(["codex"], 0, f"{role} ok", "")

        def fake_commit(message):
            events.append("commit")
            return True

        def fake_push(branch):
            events.append("push")

        with tempfile.TemporaryDirectory() as tmp:
            config_path = Path(tmp) / "orchestrator.json"
            config_path.write_text(
                """
{
  "model": "gpt-5.4-mini",
  "base_branch": "main",
  "work_branch_prefix": "agent/issue-",
  "max_cycles": 1,
  "commit_message_template": "agent(issue #{issue}): implement planned change",
  "labels": {
    "queue": "agent-run",
    "running": "agent-running",
    "blocked": "agent-blocked",
    "ready": "agent-ready-for-human",
    "failed": "agent-failed",
    "done": "agent-done"
  },
  "limits": {
    "max_changed_files": 30,
    "max_diff_lines": 1200
  },
  "forbidden_paths": [".env"],
  "test_commands": ["python -m unittest discover -s tests -p \\"test_*.py\\""],
  "codex": {
    "approval": "never",
    "builder_sandbox": "workspace-write",
    "reviewer_sandbox": "read-only",
    "planner_sandbox": "read-only",
    "extra_args": []
  },
  "pr": {
    "draft": true,
    "title_template": "Agent PR for issue #{issue}: {title}",
    "body_footer": "Generated by local Codex multi-agent orchestrator. Human review required before merge."
  }
}
""".strip(),
                encoding="utf-8",
            )

            with patch("agent_orchestrator.orchestrator.issue_view", return_value=issue), \
                patch("agent_orchestrator.orchestrator.add_label_to_issue"), \
                patch("agent_orchestrator.orchestrator.remove_label_from_issue"), \
                patch("agent_orchestrator.orchestrator.comment_issue"), \
                patch("agent_orchestrator.orchestrator.create_or_checkout_branch"), \
                patch("agent_orchestrator.orchestrator.ensure_clean_worktree"), \
                patch("agent_orchestrator.orchestrator.stage_intent_to_add"), \
                patch("agent_orchestrator.orchestrator.changed_files", return_value=["core/file.py"]), \
                patch("agent_orchestrator.orchestrator.diff_line_count", return_value=4), \
                patch("agent_orchestrator.orchestrator.has_changes", return_value=True), \
                patch("agent_orchestrator.orchestrator.branch_diff_stat", return_value=" core/file.py | 1 +"), \
                patch("agent_orchestrator.orchestrator.branch_diff_text", return_value="diff --git a/core/file.py b/core/file.py"), \
                patch("agent_orchestrator.orchestrator.current_branch", return_value="agent/issue-42"), \
                patch("agent_orchestrator.orchestrator.commit_all", side_effect=fake_commit), \
                patch("agent_orchestrator.orchestrator.push_branch", side_effect=fake_push), \
                patch("agent_orchestrator.orchestrator.pr_view_by_head", return_value={"url": "https://example.invalid/pr/1"}), \
                patch("agent_orchestrator.orchestrator._test_report", return_value=(True, "tests ok")), \
                patch("agent_orchestrator.orchestrator.run_codex_role", side_effect=fake_codex_role):
                code = run_issue(42, config_path=str(config_path), dry_run=False)

        self.assertEqual(code, 0)
        self.assertLess(events.index("commit"), events.index("reviewer"))
        self.assertLess(events.index("push"), events.index("reviewer"))


if __name__ == "__main__":
    unittest.main()
